### ISSUE TITLE
Application not running on Ubuntu 16.04

### ISSUE THREAD

**Issue by henriquedhamisch** [floripasat/grs#9]
After installation, the application does not start from the launcher.
When running from the terminal, the following error is shown:

> floripasat-grs: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by floripasat-grs)

**Comment by mgm8** [comment]
The error was replicated with a clean installation of the Ubuntu 16.04.

This error occurs because the deb package in this release had an executable compiled with Debian 10, that uses a newer version of the libgtkmm3 library.

The Ubuntu 16.04 uses the libgtkmm 3.18, and Ubuntu 18.04 and Debian 10 uses the version 3.22.

The release was updated with different packages for Ubuntu 16.04 and Ubuntu 18.04, and should work properly on each distribution.

Package for Ubuntu 16.04: [https://github.com/floripasat/grs/releases/download/v0.1/floripasat-grs_0.1-0_ubuntu16.04.deb](https://github.com/floripasat/grs/releases/download/v0.1/floripasat-grs_0.1-0_ubuntu16.04.deb)

Package for Ubuntu 18.04: [https://github.com/floripasat/grs/releases/download/v0.1/floripasat-grs_0.1-0_ubuntu18.04.deb](https://github.com/floripasat/grs/releases/download/v0.1/floripasat-grs_0.1-0_ubuntu18.04.deb)

For the next releases, the packages must be compiled and generated using their respective distributions.
